"""empty message

Revision ID: 029ce004f856
Revises: d8660e244abb
Create Date: 2023-02-13 16:10:37.028388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029ce004f856'
down_revision = 'd8660e244abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('debt',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('debt',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
