"""empty message

Revision ID: 79ecd1e1735a
Revises: 029ce004f856
Create Date: 2023-02-13 16:11:04.275909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ecd1e1735a'
down_revision = '029ce004f856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('debt',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('debt',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
